const API_URL=window.LOVER_API_URL;let rows=[];
function setSync(text,good=false,error=false){const el=document.getElementById("syncStatus");if(!el)return;if(error){el.textContent="🔴 "+text;return}el.textContent=(good?"🟢 ":"🟡 ")+text;if(good){const last=document.getElementById("lastSync");if(last)last.textContent="最后同步："+nowText()}}
function jsonp(params){return new Promise((resolve,reject)=>{const cb="ll_cb_"+Date.now()+"_"+Math.floor(Math.random()*100000);params.callback=cb;const s=document.createElement("script");const q=new URLSearchParams(params).toString();window[cb]=data=>{delete window[cb];s.remove();resolve(data)};s.onerror=()=>{delete window[cb];s.remove();reject(new Error("无法连接 Google Apps Script"))};s.src=API_URL+"?"+q;document.body.appendChild(s)})}
async function loadFromSheet(){setSync("同步中...");try{const j=await jsonp({action:"load"});if(!j.ok)throw new Error(j.message||"读取失败");rows=j.rows||[];renderAll();setSync("已同步",true)}catch(e){setSync("同步失败："+e.message,false,true);alert("同步失败："+e.message)}}
async function saveDailyToSheet(date,company,amount){const j=await jsonp({action:"saveDaily",date,company,amount});if(!j.ok)throw new Error(j.message||"储存失败");return j.row||null}
async function saveFairToSheet(location,records){const j=await jsonp({action:"saveFairBatch",location,records:JSON.stringify(records)});if(!j.ok)throw new Error(j.message||"储存失败")}
async function restoreRowsToSheet(restoredRows){const j=await jsonp({action:"restoreRows",rows:JSON.stringify(restoredRows)});if(!j.ok)throw new Error(j.message||"恢复失败")}
async function clearAllSheet(){const j=await jsonp({action:"clearAll"});if(!j.ok)throw new Error(j.message||"清空失败")}
async function seedTestDataToSheet(){const j=await jsonp({action:"seedTestData"});if(!j.ok)throw new Error(j.message||"输入测试资料失败");return j.rows||[]}
